# -*- coding: utf-8 -*-
"""Changes Visualization Choropleth Map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuLwyGOOZqGKPnpEeTeuM5DcH7FJWXEM
"""

!pip install mapclassify

from sedona.spark import *
from sedona.core.formatMapper.shapefileParser import ShapefileReader
from sedona.utils.adapter import Adapter
import geopandas
import matplotlib.pyplot as plt

config = SedonaContext.builder().appName('zillowdata')\
    .config("spark.hadoop.fs.s3a.bucket.wherobots-geodata.aws.credentials.provider","org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider")\
    .getOrCreate()
sedona = SedonaContext.create(config)

S3_URL_NE = "s3://wherobots-geodata/ne_10m_admin_2_counties/"

spatialRDD = ShapefileReader.readToGeometryRDD(sedona, S3_URL_NE)
counties_df = Adapter.toDf(spatialRDD, sedona)
counties_df.createOrReplaceTempView("counties")

type(counties_df)

counties_df.count()

SedonaKepler.create_map(counties_df, "counties")

sedona.sql("""
SELECT geometry, FIPS AS fips, NAME_EN AS name, REGION AS state FROM counties LIMIT 10
""").show()

"""Load Zillow ZHVI CSV File
Import the CSV file with the Zillow home value index data using S3.
"""

S3_URL_ZHVI = "s3://wherobots-geodata/County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv"

zhvi_df = sedona.read.format('csv').option('header','true').option('delimiter', ',').load(S3_URL_ZHVI)
zhvi_df.createOrReplaceTempView("zhvi")

zhvi_df.printSchema()

sedona.sql("""
SELECT RegionName,StateName, State, Metro, StateCodeFIPS, MunicipalCodeFIPS, `2000-01-31` FROM zhvi LIMIT 10
""").show()

"""Joining ZHVI And County Geometries¶
So we now have two tables zhvi and counties - let's join them together so we can plot current home value per county. To do that we'll use the FIPS code which uniquely identifes each county. The zhvi table breaks the FIPS code out into the state and municipal components so we'll need to combine then so we can join against the counties table.
"""

zhvi_county_df = sedona.sql("""
SELECT CAST(zhvi.`2023-10-31` AS float) AS value, zhvi.RegionName As name, counties.geometry
FROM zhvi
JOIN counties
ON CONCAT('US', zhvi.StateCodeFIPS, zhvi.MunicipalCodeFIPS) = counties.FIPS
WHERE NOT zhvi.State IN ('HI', 'AK')
""")

zhvi_county_df.show(5)

zhvi_county_df.printSchema()

type(zhvi_county_df)

SedonaPyDeck.create_choropleth_map(zhvi_county_df,plot_col="value")

"""Use matplotlib to create a choropleth map by converting our zhvi_county_df Sedona DataFrame to a GeoDataFrame."""

zhvi_gdf = geopandas.GeoDataFrame(zhvi_county_df.toPandas(), geometry="geometry")
zhvi_gdf.crs = {"init": "epsg:4326"}
zhvi_gdf.to_crs(epsg=6350)

ax = zhvi_gdf.plot(
    column="value",
    scheme="JenksCaspall",
    cmap="YlGn",
    legend=True,
    legend_kwds={"title": "Median Home Value($)", "fmt": "{:.0f}", "loc": "lower right"},
    missing_kwds={
        "color": "lightgrey",
        "edgecolor": "red",
        "hatch": "///",
        "label": "Missing values"
    },
    figsize=(12,9)
)

ax.set_axis_off()
ax.set_title("Median Home Value By County, Oct 2023")
ax.annotate("Data from Zillow, 2023 ZHVI",(-125,25))

plt.savefig("zhvi.png",dpi=300)

"""Visualizing Change In Home Value
Calculate the change in home value over the last 5 years and visualize the spatial distribution.

In our SQL query calculate the percent change in home value from 2018 to 2023. Compute the centroid of each county to annotate the map.
"""

delta_county_df = sedona.sql("""
SELECT
  ((CAST(zhvi.`2023-10-31` AS float) - CAST(zhvi.`2018-10-31` AS float)) / (CAST(zhvi.`2018-10-31` AS float)) * 100 )  AS delta,
  zhvi.RegionName As name, zhvi.Statename AS state,counties.geometry, ST_Centroid(counties.geometry) AS centroid
FROM zhvi
JOIN counties
ON CONCAT('US', zhvi.StateCodeFIPS, zhvi.MunicipalCodeFIPS) = counties.FIPS
WHERE NOT zhvi.State IN ('HI', 'AK')
""")

delta_county_df.show(5)

